### ISSUE TITLE
When I execute "make install" in Ubuntu 16.04, I am prompted with an "SSL error"

### ISSUE THREAD

**Issue by iscaszmh** [PeterHuewe/tpm-emulator#34] opened 2018-07-26 08:05 UTC
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
-- Up-to-date: /usr/local/bin/tpmd

**Comment by PeterHuewe** [comment] 2018-09-15 20:36
This is because ubuntu 16.04 and up use signed kernel modules.
I would have to create a dkms package to be included in ubuntu.
Otherwise not much I can do - since the signing key is not available to me (as it would defeat the whole purpose of having signed modules).

**Comment by PeterHuewe** [comment] 2018-12-12 23:35
It's more or less a "wontfix" so I close it for now.
Nothing I can do.

**Closed by PeterHuewe** 2018-12-12 23:35 UTC
Labels: wontfix

**Comment by PeterHuewe** [comment] 2018-12-12 23:36
Duplicate of #31
